const order = {
  Order: {
    Address: {
      Street: ' ',
      City: ' ',
      Region: ' ',
      PostalCode: ' ',
      Type: 'House',
      StreetName: ' ',
      StreetNumber: ' ',
    },
    Coupons: [
      {
        Code: ' ',
        Qty: 1,
        ID: 1,
        IsBelowMinimumOrderAmount: false,
        IsBelowMinimumPaymentAmount: false,
        Tags: {
          Hash: ' ',
        },
      },
    ],
    CustomerID: '',
    Email: '',
    Extension: '',
    FirstName: '',
    LastName: '',
    LanguageCode: 'en',
    OrderChannel: 'OLO',
    OrderID: ' ',
    OrderMethod: 'Web',
    OrderTaker: null,
    Payments: [],
    Phone: '',
    PhonePrefix: '',
    Products: [
    ],
    ServiceMethod: '',
    SourceOrganizationURI: 'order.dominos.com',
    StoreID: '',
    Tags: {},
    Version: '1.0',
    NoCombine: true,
    Partners: {},
    HotspotsLite: false,
    OrderInfoCollection: [],
  },
};
